language: cpp
sudo:     required

services:
    - docker

compiler:
    - gcc

env:
    - OPT=-O2 CXXSTD=1y NLS=false

services:
    - docker

before_install:
    - docker build -t wesnoth_cpp14 -f utils/travis/dockerfile.txt utils/travis
#    - export TARGETS="wesnoth wesnothd campaignd test"
#    - export EXTRA_FLAGS_RELEASE=""
#
#    - if [[ "$OPT" == "-O0" ]] && [[ "$CXX" == "clang++" ]]; then export EXTRA_FLAGS_RELEASE="-O0 -Wno-deprecated-declarations -Wno-literal-suffix -Wno-deprecated-register"; fi

install:
#    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#    - travis_wait sudo apt-get update -qq
#    - travis_wait sudo apt-get install -qq libboost-filesystem-dev libboost-iostreams-dev libboost-random-dev libboost-program-options-dev libboost-regex-dev libboost-system-dev libboost-test-dev libboost-locale-dev libboost-thread-dev libcairo2-dev libfribidi-dev libpango1.0-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev gdb moreutils scons xvfb cmake
#    - sudo apt-get install -qq g++-5;

script:
    - docker run -v `pwd`:/build wesnoth_cpp14
      scons cxxtool=g++-5 --debug=time build=release extra_flags_config=-pipe extra_flags_release="$EXTRA_FLAGS_RELEASE" strict=false $TARGETS cxx_std=$CXXSTD nls=$NLS jobs=2;
