language: objective-c
before_install:
- brew update
- brew tap homebrew/games
- brew install wesnoth --only-dependencies --verbose -j2
script:
#- brew install wesnoth --HEAD --verbose -j2
- scons wesnoth OS_ENV=true -j2 nls=false
deploy:
  provider: releases
  api_key:
    secure: Yc7R24d1IUd/ymiR9TabjY0S73SFZdaifIXA/I1cavXeSd+HHgfuHvkjZhotgmOs2XMNwIwuGK/qGgMRw2VyFsVjLswVrMJPAwscL02rz7Nn/opdMAj1tsAsh2IdFrzmB/AlbtsbClXPqdwla/8PWcBmvDriDMTFXoWFD/gPA84=
  file: wesnoth
  on:
    repo: cbeck88/wesnoth
    branch: deploy-os-x
