language: objective-c
before_install:
- git fetch --tags
- export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig:$PKG_CONFIG_PATH
- export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
- env

- brew update
- brew tap homebrew/games
- brew install wesnoth --only-dependencies --verbose -j2
- env
script:
#- brew install wesnoth --HEAD --verbose -j2
- scons wesnoth OS_ENV=true -j2 nls=false gettextdir=`brew --prefix gettext`
- ls

deploy:
  provider: releases
  api_key:
    secure: Yc7R24d1IUd/ymiR9TabjY0S73SFZdaifIXA/I1cavXeSd+HHgfuHvkjZhotgmOs2XMNwIwuGK/qGgMRw2VyFsVjLswVrMJPAwscL02rz7Nn/opdMAj1tsAsh2IdFrzmB/AlbtsbClXPqdwla/8PWcBmvDriDMTFXoWFD/gPA84=
  file: wesnoth
  skip_cleanup: true
  on:
    repo: cbeck88/wesnoth
    tags: true
    all_branches: true
